[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_143'
old = '''
セットボタンを押す
LV.６で再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_144'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_146'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_149'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_145'
old = '''
セットボタンを連続して押す
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_147'
old = '''
セットボタンを押す
発現後、再度セットボタンを押すと起爆
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_150'
old = '''
セットボタンを押す
展開後、その場に留まることで展開時間を延長
ヒールブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_148'
old = '''
セットボタンを押す
発現後、再度セットボタンを押すと攻撃
アタックブーストで強化可能 
<COL ff7878>バリアの霊力最大時の発動で戦甲へのカウンターに特化</COL>'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_153'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_188'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_195'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_196'
old = '''
セットボタンを押す
ヒールブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_193'
old = '''
セットボタンを押す
再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_194'
old = '''
セットボタンを押す
再度セットボタンを押すと派生斬り
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_233'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_10_234'
old = '''
セットボタンを押す
アタックブーストで強化可能'''
