[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_56'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_58'
old = '''
セットボタンを押す
<KC JUMP>で終了
<PADM>右スティック<KEYM>マウス移動</KEYM>で照射角度を調整'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_59'
old = '''
セットボタンを押す
<KC JUMP>で終了
<PADM>右スティック<KEYM>マウス移動</KEYM>で照射角度を調整'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_60'
old = 'セットボタンを押す'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_62'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_61'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_63'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_57'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_65'
old = '''
セットボタンを押す
<KC JUMP>で終了
<PADM>右スティック<KEYM>マウス移動</KEYM>で照射角度を調整'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_66'
old = '敵の攻撃を引きつけてセットボタンを押す'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_64'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_67'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_136'
old = '''
セットボタンを押す
<KC JUMP>で終了
<PADM>右スティック<KEYM>マウス移動</KEYM>で照射角度を調整'''
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_135'
old = 'セットボタンを押す'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_170'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_171'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_172'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_173'
old = 'セットボタンを押して詠唱、詠唱完了で発動'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_205'
old = 'セットボタンを押す'
[[message]]
key = 'CUSTOM_SKILL_COMMAND_05_206'
old = 'セットボタンを押す'
