[[message]]
key = 'CUSTOM_SKILL_NAME_04_48'
old = 'アタックライザー'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_49'
old = 'ディフェンスライザー'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_46'
old = 'セラフィムフラップ'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_50'
old = 'ガードビット'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_44'
old = 'ヒーリングスポット'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_45'
old = 'キュアスポット'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_47'
old = 'セイクリッドシャイン'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_54'
old = 'ソウルエクスプロージョン'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_55'
old = 'ソリッドライザー'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_52'
old = 'エナジースポット'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_53'
old = 'ゾーンオブザゴッド'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_51'
old = 'クイックチャージ'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_133'
old = 'ソラースライザー'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_134'
old = 'ブラストアディション'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_166'
old = 'ソラースライザー 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_167'
old = 'ソラースライザー 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_168'
old = 'セラフィムフラップ 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_169'
old = 'セラフィムフラップ 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_218'
old = 'キュアスポット 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_04_217'
old = 'キュアスポット 技'
