[[message]]
key = 'CUSTOM_SKILL_NAME_06_68'
old = 'ファイアストーム'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_72'
old = 'サンダーケージ'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_74'
old = 'ブラックヘイズ'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_71'
old = 'フロストスパイク'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_69'
old = 'フレイムウォール'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_73'
old = 'クレセントブレード'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_75'
old = 'ロックビート'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_70'
old = 'メテオフォール'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_76'
old = 'サンダーレイン'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_78'
old = 'ダークネスミスト'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_77'
old = 'ブリザードアロー'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_79'
old = 'プロミネントスフィア'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_137'
old = 'アイシクルピアス'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_138'
old = 'ライトニングステイク'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_176'
old = 'ダークネスミスト 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_177'
old = 'ダークネスミスト 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_178'
old = 'サンダーケージ 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_179'
old = 'サンダーケージ 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_221'
old = 'フレイムウォール 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_06_222'
old = 'フレイムウォール 技'
