[[message]]
key = 'CUSTOM_SKILL_INFO_02_20'
old = '''
敵を追従する猛ダッシュの斬りつけ攻撃を放つ
初撃が当たると連続で斬り返しを放つ
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長／
斬り返し回数増加（１→３）</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_21'
old = '''
一歩踏み込み、敵を上空へ斬り上げる
ボタンの追加入力で追撃する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_24'
old = '''
瞬時に身を引き、すぐさま前方に蹴りを放つ
敵の攻撃を回避しつつ繰り出せば威力が上昇する
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６でモーション変化／攻撃ヒット数増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_22'
old = '''
シーカーロープを投げて敵を捉え、
手前に引き寄せる
<COL ffdc78>LV UP毎に引き寄せる力の上昇
LV.６で攻撃範囲拡張/捕捉敵数増加（１→３）</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_29'
old = '''
空中からシーカーロープを放って地面にひっかけ、
地上へ急降下攻撃を繰り出す。空中でも発動可能
高所から行うことで威力が上昇し気絶させやすくなる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で周囲の敵をのけぞらせることが可能</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_23'
old = '''
前方に飛び蹴りを繰り出し、敵を踏み台にして
上空へ跳び上がる
空中でも発動可能
<COL ffdc78>LV UP毎にジャンプ力上昇
LV.６で敵のガード状態を崩すことが可能</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_25'
old = '''
自身を通常の構え姿勢に戻し、様々な動作の
スキを消すことができる（連続では行えない）
空中でも発動可能
<COL ffdc78>LV UP毎に再発禁止時間が短縮
LV.６で拘束中を除きいつでも発動可能</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_26'
old = '''
地面に火薬を設置し、
遠方から導火線に着火して爆発させる
<COL ffdc78>LV UP毎に攻撃威力の上昇／仕込み時間短縮
LV.６で攻撃ヒット数増加／爆風に風圧追加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_30'
old = '''
ダガーを高速回転させ、敵を巻き込み斬りつける
<PADM>左スティック<KEYM>移動キー</KEYM>で任意方向に移動できる
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長／攻撃ヒット数増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_31'
old = '''
シーカーロープを放って敵を捕らえ、反動を利用して
気絶を誘うスライディング攻撃を繰り出す
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で移動距離が延長</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_27'
old = '''
自身の体に炎をまとい触れた敵にダメージを与える
さらに武器の攻撃属性を炎にする
ただし、発動中は自身の体力が徐々に減少する
<COL ffdc78>LV UP毎に炎属性威力の上昇／体力減少速度軽減
LV.６で最大持続時間が延長</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_28'
old = '''
敵の攻撃を受け流し、瞬時に背後に回り込んで
致命の一撃を与える
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加／受付時間延長／
攻撃アクション中であればいつでも発動可能</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_129'
old = '''
自身の周囲に火薬を撒き、
ダガーで弾いて爆発を起こす
空中でも発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_130'
old = '''
シーカーロープを放って敵を捕らえ、反動を利用して
激しく斬りこみながら距離を詰める
ボタン追加入力で追撃を繰り出す。空中でも発動可能
<COL ffdc78>LV UP毎に攻撃威力の上昇
LV.６で攻撃ヒット数増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_160'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
気絶攻力が増加'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_161'
old = '''
【ＥＸ追加効果】
空中で使用可能になる
チャンス攻力が増加
疲労攻力が増加'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_158'
old = '''
【ＥＸ追加効果】
ダメージ量が増加
<COL ff7878>獣／有翼／侵食系の敵に与えるダメージ量が増加</COL>'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_159'
old = '''
【ＥＸ追加効果】
空中使用回数が増加（１→２）
吹き飛ばし力がやや増加'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_213'
old = '''
【ＥＸ追加効果】
空中発動時１度だけモーションが変化しダメージが追加
攻撃スキルを敵に接触させる／着地／しがみつきにより
カスタムスキルＥＸ追加効果を空中で再度発動可能'''
[[message]]
key = 'CUSTOM_SKILL_INFO_02_214'
old = '''
【ＥＸ追加効果】
発動時と跳び上がり時に敵の攻撃をすり抜ける
空中発動時に短剣による攻撃が追加'''
