[[message]]
key = 'CUSTOM_SKILL_NAME_07_80'
old = '突き上げ斬り'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_82'
old = '魔人駆け'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_81'
old = '柄打ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_83'
old = 'かわし斬り'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_84'
old = '大輪斬'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_85'
old = '魔人崩し'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_87'
old = '天衝刃'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_86'
old = '無心斬'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_90'
old = '凌魔の身構え'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_89'
old = '大風車斬り'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_91'
old = '飛龍突'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_88'
old = '殲魔剣風斬'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_139'
old = '大牙抉り'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_140'
old = '地衝牙'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_180'
old = '魔人駆け 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_181'
old = '魔人駆け 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_182'
old = '柄打ち 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_183'
old = '柄打ち 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_225'
old = 'かわし斬り 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_07_226'
old = 'かわし斬り 技'
