[[message]]
key = 'CUSTOM_SKILL_NAME_03_32'
old = '連なり射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_37'
old = '貫き射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_33'
old = '扇射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_34'
old = '仕込み爆音矢'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_36'
old = '降らし射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_38'
old = '渦巻き射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_39'
old = '紅蓮爆矢'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_35'
old = '剛力射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_42'
old = '逆縮地'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_40'
old = '降らし爆炎矢'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_41'
old = '矢継ぎ嵐'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_43'
old = '鬼神射ち'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_131'
old = '天穹爆矢'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_132'
old = '穿ち接射'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_162'
old = '連なり射ち 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_163'
old = '連なり射ち 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_164'
old = '渦巻き射ち 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_165'
old = '渦巻き射ち 技'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_197'
old = '剛力射ち 剛'
[[message]]
key = 'CUSTOM_SKILL_NAME_03_198'
old = '剛力射ち 技'
