[[message]]
key = 'NORMAL_SKILL_NAME_08_113'
old = '<PADM>闘波の構え<KEYM>構えの変更（闘波の構え）'
[[message]]
key = 'NORMAL_SKILL_NAME_08_114'
old = '闘波の魔眼'
[[message]]
key = 'NORMAL_SKILL_NAME_08_115'
old = '闘波の矢'
[[message]]
key = 'NORMAL_SKILL_NAME_08_116'
old = '闘波の集中'
[[message]]
key = 'NORMAL_SKILL_NAME_08_117'
old = '<PADM>助真の構え<KEYM>構えの変更（助真の構え）'
[[message]]
key = 'NORMAL_SKILL_NAME_08_118'
old = '助真の魔眼'
[[message]]
key = 'NORMAL_SKILL_NAME_08_119'
old = '助真の矢'
[[message]]
key = 'NORMAL_SKILL_NAME_08_120'
old = '助真の集中'
[[message]]
key = 'NORMAL_SKILL_NAME_08_121'
old = '前蹴り'
[[message]]
key = 'NORMAL_SKILL_NAME_08_122'
old = '癒しの装'
[[message]]
key = 'NORMAL_SKILL_NAME_08_123'
old = '狙いの神眼'
[[message]]
key = 'NORMAL_SKILL_NAME_08_135'
old = '奮わせ直魔矢'
