[[message]]
key = 'bazaar_msg_itemsearch_en'
old = 'Item Search'
[[message]]
key = 'bazaar_msg_itemsearch_jp'
old = '商品検索'
[[message]]
key = 'bazaar_msg_categorysearch_en'
old = 'Category Search'
[[message]]
key = 'bazaar_msg_categorysearch_jp'
old = 'カテゴリ'
[[message]]
key = 'bazaar_msg_cs_categorysort'
old = '＞'
[[message]]
key = 'bazaar_msg_cs_rank'
old = 'ランク'
[[message]]
key = 'bazaar_msg_cs_morethan'
old = '以上'
[[message]]
key = 'bazaar_msg_bt_search'
old = '検索'
[[message]]
key = 'bazaar_msg_freewordsearch_en'
old = 'Free Word Search'
[[message]]
key = 'bazaar_msg_freewordsearch_jp'
old = 'フリーワード検索'
[[message]]
key = 'bazaar_msg_disp_itemname'
old = 'アイテム名'
[[message]]
key = 'bazaar_msg_disp_number'
old = '件数'
[[message]]
key = 'bazaar_msg_searchresult_num'
old = '件'
[[message]]
key = 'bazaar_msg_itemlist_disp_unitprice'
old = '単価'
[[message]]
key = 'bazaar_msg_itemlist_disp_price'
old = '価格'
[[message]]
key = 'bazaar_msg_itemlist_disp_number_num'
old = '個'
[[message]]
key = 'bazaar_msg_buy_distribution'
old = '購入する個数を振分けてください'
[[message]]
key = 'bazaar_msg_bt_buy'
old = '購入'
[[message]]
key = 'bazaar_msg_bt_cancel'
old = 'キャンセル'
[[message]]
key = 'bazaar_msg_buy_confirmation'
old = '''
以下の内容で購入します。よろしいですか？

　アイテム：<NAME ITEM>
　合計個数：<VAL>個
　合計価格：<VAL GOLD>'''
[[message]]
key = 'bazaar_msg_bt_yes'
old = 'はい'
[[message]]
key = 'bazaar_msg_bt_no'
old = 'いいえ'
[[message]]
key = 'bazaar_msg_info_switch'
old = '情報切替'
[[message]]
key = 'bazaar_msg_info_trade'
old = '取引成立相場'
[[message]]
key = 'bazaar_msg_info_exhibit'
old = '出品中相場'
[[message]]
key = 'bazaar_msg_info_disp_tradingday'
old = '日付'
[[message]]
key = 'bazaar_msg_info_disp_number'
old = '個数'
[[message]]
key = 'bazaar_msg_exhibit_set_unitprice'
old = '単価設定'
[[message]]
key = 'bazaar_msg_exhibit_set_unitprice_limit'
old = '※<VAL GOLD> ～ <VAL GOLD>まで'
[[message]]
key = 'bazaar_msg_exhibit_set_number'
old = '個数設定'
[[message]]
key = 'bazaar_msg_bt_decision'
old = '決定'
[[message]]
key = 'bazaar_msg_exhibit_confirmation'
old = '''
以下の内容で出品します。よろしいですか？

　アイテム：<NAME ITEM>
　出品個数：<VAL>個
　出品価格：<VAL GOLD>
　売上時手数料(<VAL>%)：<VAL GOLD>'''
[[message]]
key = 'bazaar_msg_announce_exhibited'
old = '<NAME ITEM>を出品しました'
[[message]]
key = 'bazaar_msg_situation_en'
old = 'Sell List'
[[message]]
key = 'bazaar_msg_situation_jp'
old = '出品状況'
[[message]]
key = 'bazaar_msg_situation_disp_exhibiting'
old = '出品中：'
[[message]]
key = 'bazaar_msg_situation_disp_totalsales'
old = '売上合計：'
[[message]]
key = 'bazaar_msg_bt_salesreceipt'
old = '売上の受け取り'
[[message]]
key = 'bazaar_msg_situation_exhibition_poss'
old = '出品可能'
[[message]]
key = 'bazaar_msg_situation_exhibition_imposs'
old = 'あと<COL FFFF00><JKAN HM></COL>で利用できます'
[[message]]
key = 'bazaar_msg_situation_congrats'
old = 'おめでとうございます！ 取引成立しました！'
[[message]]
key = 'bazaar_msg_announce_get_money'
old = 'バザー売上 <VAL GOLD>を受け取りました'
[[message]]
key = 'bazaar_msg_bt_stop'
old = '取り消し'
[[message]]
key = 'bazaar_msg_bt_re_exhibit'
old = '再出品'
[[message]]
key = 'bazaar_msg_stop_confirmation'
old = '''
以下の出品を取り消します。よろしいですか？
(取り消したアイテムは保管ボックスに送ります)

　アイテム：<NAME ITEM>
　出品個数：<VAL>個
　設定価格：<VAL GOLD>'''
[[message]]
key = 'bazaar_msg_announce_stop'
old = '<NAME ITEM>を保管ボックスに移動しました'
[[message]]
key = 'bazaar_msg_re_exhibit_set_unitprice'
old = '単価の再設定'
[[message]]
key = 'bazaar_msg_re_exhibit_confirmation'
old = '''
以下の内容で再出品します。よろしいですか？

　アイテム：<NAME ITEM>
　出品個数：<VAL>個
　出品価格：<VAL GOLD>
　売上時手数料(<VAL>%)：<VAL GOLD>'''
[[message]]
key = 'bazaar_msg_announce_re_exhibited'
old = '<NAME ITEM>を再出品しました'
[[message]]
key = 'bazaar_msg_announce_buy'
old = '<NAME ITEM>を購入しました'
[[message]]
key = 'bazaar_msg_disp_search_info'
old = '左のメニューから検索してください'
[[message]]
key = 'bazaar_msg_disp_search_notfound'
old = '一致する情報は見つかりませんでした'
[[message]]
key = 'bazaar_msg_announce_error_buy'
old = '購入に失敗しました'
[[message]]
key = 'bazaar_msg_announce_error_exhibit'
old = '出品に失敗しました'
[[message]]
key = 'bazaar_msg_announce_error_stop'
old = '取り消しに失敗しました'
[[message]]
key = 'bazaar_msg_announce_error_info'
old = '情報の取得に失敗しました'
[[message]]
key = 'bazaar_msg_announce_error_exhibit_over'
old = '出品可能数が０のため、新たに出品できません'
[[message]]
key = 'bazaar_msg_announce_error_possession_full '
old = 'アイテムバッグと保管ボックスに空き枠が無いため購入できません'
[[message]]
key = 'bazaar_msg_announce_error_stop_storage_full'
old = '保管ボックスに空き枠が無いため取り消しできません'
[[message]]
key = 'bazaar_msg_shortcut_exhibit'
old = '出品へのショートカット'
[[message]]
key = 'bazaar_msg_announce_error_bazaaritem0'
old = 'バザーに出品できるアイテムを持っていません'
[[message]]
key = 'bazaar_msg_disp_snatching_notfound'
old = '''
購入できるアイテムは見つかりませんでした
前の画面に戻ってください

（他のプレイヤーに購入された、もしくは
出品を取り消した等の可能性があります）'''
[[message]]
key = 'bazaar_msg_announce_many_search'
old = '一致する情報が多いため、すべてを取得できませんでした'
[[message]]
key = 'bazaar_msg_exhibit_set_number_limit'
old = '※<VAL> 個まで'
[[message]]
key = 'bazaar_msg_disp_access_frequency_error'
old = '''
サーバーへのアクセス頻度が高いため
一定時間、商品検索のご利用を制限いたします
時間を置いてもう一度お試しいただくか
アクセス頻度を下げてご利用いただきますよう
お願いいたします'''
