[[message]]
key = 'hud_job_hunter_normal_arrow'
old = '通常矢'
[[message]]
key = 'hud_disp_level'
old = 'LV.'
[[message]]
key = 'hud_quest_qo'
old = 'Quest Owner'
[[message]]
key = 'hud_quest_gm'
old = 'Grand Mission'
[[message]]
key = 'hud_job_hunter_change_arrow'
old = '矢切替'
[[message]]
key = 'hud_job_sealedsage_change_attribution'
old = '属性切替'
[[message]]
key = 'hud_job_unequipped'
old = 'None'
[[message]]
key = 'hud_status_standby'
old = 'スタンバイOK'
[[message]]
key = 'hud_status_away'
old = '離席中'
[[message]]
key = 'hud_status_event'
old = 'イベント'
[[message]]
key = 'hud_quest_qg_time'
old = 'Time'
[[message]]
key = 'hud_quest_qg_point'
old = 'Score'
[[message]]
key = 'hud_quest_qg_pt'
old = 'pt'
[[message]]
key = 'hud_quest_qg_sec'
old = 'sec'
[[message]]
key = 'hud_status_ailment_sec'
old = '秒'
[[message]]
key = 'hud_status_ailment_stamina'
old = 'スタミナ回復'
[[message]]
key = 'hud_get_announce_bo'
old = '<VAL> <UNIT BO>'
[[message]]
key = 'hud_get_announce_g'
old = '<VAL> <UNIT G>'
[[message]]
key = 'hud_get_announce_r'
old = '<VAL> <UNIT R>'
[[message]]
key = 'hud_get_announce_xp'
old = '<VAL> <UNIT XP>'
[[message]]
key = 'hud_quest_ann_caution_deco'
old = 'Defeat the enemy !'
[[message]]
key = 'hud_pawn_ann_lost'
old = '<VAL> がポーン郷にある異界の狭間へ送られました'
[[message]]
key = 'hud_pawn_ann_rescue_start'
old = '<VAL> を襲いかかる敵から救出せよ'
[[message]]
key = 'hud_pawn_ann_rescue_failed'
old = '<VAL> の呪縛を解くことができなかった'
[[message]]
key = 'hud_pawn_ann_rescue_clear'
old = '<VAL> の呪縛が解け、リムの淵辺で目を覚ました'
[[message]]
key = 'hud_pawn_ann_resurrection'
old = '<VAL> が復活し、待機状態に戻りました'
[[message]]
key = 'hud_disp_infinity'
old = '∞'
[[message]]
key = 'hud_get_announce_pawnlvup'
old = '<NAME PAWN>が<LEVEL>にUPしました'
[[message]]
key = 'hud_enemy_nodamage'
old = 'Invulnerable'
[[message]]
key = 'hud_enemy_engage'
old = 'In Battle !'
[[message]]
key = 'hud_gauge_sorcery_bonus'
old = '× <VAL>'
[[message]]
key = 'hud_gauge_sorcery_button'
old = '<KC CHANGE_MODE>'
[[message]]
key = 'hud_quest_em'
old = 'Extreme Mission'
[[message]]
key = 'hud_status_disconnect'
old = '回線切断中'
[[message]]
key = 'hud_job_alchemist_normal_medal'
old = '遅延のエリクシル'
[[message]]
key = 'hud_job_alchemist_change_medal'
old = 'エリクシル切替'
[[message]]
key = 'hud_skill_move'
old = '発動'
[[message]]
key = 'hud_charges_others'
old = ' その他×<VAL>'
[[message]]
key = 'hud_recommend_level'
old = 'LV.%d'
[[message]]
key = 'hud_get_announce_bo_ex'
old = '<VAL> <VAL> <UNIT BO>'
[[message]]
key = 'hud_get_announce_r_ex'
old = '<VAL> <VAL> <UNIT R>'
[[message]]
key = 'hud_get_announce_xp_ex'
old = '<VAL> <VAL> <UNIT XP>'
[[message]]
key = 'hud_generalpurpose_clear_deco'
old = 'Defeated the enemy !'
[[message]]
key = 'hud_change_tx_tank'
old = '<PADM><ICON PAD_L></PADM><KEYM><ICON MOUSE></KEYM>'
[[message]]
key = 'hud_gauge_xp_next'
old = 'Next '
[[message]]
key = 'hud_get_announce_g_ex'
old = '<VAL> <VAL> <UNIT G>'
[[message]]
key = 'hud_get_announce_goldstone'
old = '<VAL> @'
[[message]]
key = 'hud_get_announce_silvertickets'
old = '<VAL> _|'
[[message]]
key = 'hud_map_guide_lock'
old = 'ロック'
[[message]]
key = 'hud_map_guide_scaling'
old = '拡縮'
[[message]]
key = 'hud_map_guide_freemarker'
old = 'フリーマーカー'
[[message]]
key = 'hud_map_guide_cursor'
old = 'カーソル移動'
[[message]]
key = 'hud_map_guide_operation'
old = 'ミニマップ操作'
[[message]]
key = 'hud_map_guide_zoom'
old = 'ズームイン/アウト'
[[message]]
key = 'hud_get_announce_rp'
old = '<VAL> <UNIT RP>'
[[message]]
key = 'hud_get_announce_rp_ex'
old = '<VAL> <VAL> <UNIT RP>'
[[message]]
key = 'hud_commongauge_button_barrage_square'
old = '<KC ATTACK1>'
[[message]]
key = 'hud_commontext_sorcery_cs13'
old = '氷柱を放つ：'
[[message]]
key = 'hud_commontext_sorcery_cs14'
old = 'アンカーを消滅させる：<KC TOUCH>'
[[message]]
key = 'hud_commongauge_button_barrage_triangle'
old = '<KC ATTACK2>'
[[message]]
key = 'hud_commontext_all_reliefcancel'
old = '救済を中断する：<KC JUMP>'
[[message]]
key = 'hud_commontext_cs_button_square'
old = '<KC ATTACK1>'
[[message]]
key = 'hud_commontext_cs_button_triangle'
old = '<KC ATTACK2>'
[[message]]
key = 'hud_job_spiritlancer_change_item'
old = 'アイテム切替(仮)'
[[message]]
key = 'hud_job_spiritlancer_normal_item'
old = '【仮0】 HP回復'
[[message]]
key = 'hud_get_announce_pp'
old = '<VAL> <UNIT PP>'
[[message]]
key = 'hud_get_announce_pp_ex'
old = '<VAL> <VAL> <UNIT PP>'
[[message]]
key = 'hud_caution_announce_warning_deco'
old = 'Defeat the dungeon enemy !'
[[message]]
key = 'hud_caution_announce_clear_warning_deco'
old = 'Defeated the dungeon enemy !'
[[message]]
key = 'hud_commontext_spiritlancer_nospirit'
old = 'No Spirits !'
[[message]]
key = 'hud_commontext_spiritlancer_cs08'
old = '支援を解除する：<KC JUMP>'
[[message]]
key = 'hud_map_guide_auto_scaling_lock'
old = '拡大固定'
[[message]]
key = 'hud_map_guide_auto_scaling_unlock'
old = '拡大固定解除'
[[message]]
key = 'hud_announce_clan_dungeon_unlock'
old = '新たなクランダンジョンが解放されました'
[[message]]
key = 'hud_announce_first_discovered'
old = 'おめでとうございます！ この新種の第一発見者になりました！'
[[message]]
key = 'hud_announce_new_species_discovered'
old = 'お見事！ 新種のマンドラゴラを発見しました！'
[[message]]
key = 'hud_get_announce_dp'
old = '<VAL> <UNIT DP>'
[[message]]
key = 'hud_get_announce_dp_ex'
old = '<VAL> <VAL> <UNIT DP>'
[[message]]
key = 'hud_get_announce_hb'
old = '<VAL> <UNIT HB>'
[[message]]
key = 'hud_get_announce_hb_ex'
old = '<VAL> <VAL> <UNIT HB>'
[[message]]
key = 'hud_ordeal_ann_start'
old = '特殊条件を満たし、英霊の試練を攻略せよ'
[[message]]
key = 'hud_ordeal_ann_clear'
old = '特殊条件を満たし、英霊の試練を突破した'
[[message]]
key = 'hud_ordeal_ann_failed'
old = '特殊条件を満たせず、英霊の試練に失敗した'
[[message]]
key = 'hud_get_announce_ms'
old = '<VAL> =*'
[[message]]
key = 'hud_commontext_alchemist_cs12'
old = '支援を解除する：<KC JUMP>'
[[message]]
key = 'hud_get_announce_gdm'
old = '<VAL> $#'
[[message]]
key = 'hud_get_announce_sdm'
old = '<VAL> {#'
[[message]]
key = 'hud_get_announce_rdm'
old = '<VAL> }#'
[[message]]
key = 'hud_announce_bbi_clear'
old = '《%s》攻略！'
[[message]]
key = 'hud_announce_bbi_comp'
old = '%sを踏破した！'
[[message]]
key = 'hud_notice_no_charm_gauge'
old = '魔力が%sゲージ以上ありません'
[[message]]
key = 'hud_notice_no_charm_stack'
old = '魔力が%sスタック以上ありません'
