[[message]]
key = 'QUEST_MSG_LB_REC'
old = '推奨'
[[message]]
key = 'QUEST_MSG_LB_PROV'
old = '受注条件'
[[message]]
key = 'QUEST_MSG_LB_NOTHING'
old = 'なし'
[[message]]
key = 'QUEST_MSG_LB_REQ'
old = '依頼内容'
[[message]]
key = 'QUEST_MSG_LB_REWARD'
old = '報酬'
[[message]]
key = 'QUEST_MSG_LB_EXP'
old = '経験値'
[[message]]
key = 'QUEST_MSG_LB_G'
old = 'ゴールド'
[[message]]
key = 'QUEST_MSG_LB_RIM'
old = 'リム'
[[message]]
key = 'QUEST_MSG_PRIOD'
old = '<VAL>まで'
[[message]]
key = 'QUEST_MSG_LB_NOREWARD'
old = '報酬アイテムなし'
[[message]]
key = 'QUEST_MSG_MASK'
old = '？？？？？'
[[message]]
key = 'QUEST_MSG_TITLE01'
old = 'Quest Log'
[[message]]
key = 'QUEST_MSG_TITLE02'
old = 'クエストログ'
[[message]]
key = 'QUEST_MSG_MENU_ENPRI'
old = '優先クエストに設定'
[[message]]
key = 'QUEST_MSG_ACCEPTED'
old = '受注数：'
[[message]]
key = 'QUEST_MSG_MENU'
old = 'メニュー'
[[message]]
key = 'QUEST_MSG_LB_ABS'
old = '概要'
[[message]]
key = 'QUEST_MSG_LB_PROG'
old = '進行'
[[message]]
key = 'QUEST_MSG_TAB_MYQ'
old = 'マイクエスト'
[[message]]
key = 'QUEST_MSG_TAB_PTQ'
old = 'パーティークエスト情報'
[[message]]
key = 'QUEST_MSG_CG_MAIN'
old = 'メインクエスト'
[[message]]
key = 'QUEST_MSG_CG_GRAND'
old = 'ワールドクエスト'
[[message]]
key = 'QUEST_MSG_CG_SOLO'
old = 'パーソナルクエスト'
[[message]]
key = 'QUEST_MSG_LB_NSTEP'
old = '次の目的'
[[message]]
key = 'QUEST_MSG_LB_CLEARED'
old = 'クリア回数'
[[message]]
key = 'QUEST_MSG_LB_ADDINFO'
old = 'クリア回数による追加情報'
[[message]]
key = 'QUEST_MSG_LB_AREAP'
old = 'エリア名声度：<NAME AREA_NAME>'
[[message]]
key = 'QUEST_MSG_NAME_AREA'
old = 'エリア名'
[[message]]
key = 'QUEST_MSG_UN_AP'
old = 'AP'
[[message]]
key = 'QUEST_MSG_LB_BONUS'
old = 'ボーナス'
[[message]]
key = 'QUEST_MSG_LB_CHARGINFO'
old = '課金情報'
[[message]]
key = 'QUEST_MSG_LB_GOAL'
old = '目的'
[[message]]
key = 'QUEST_MSG_OPERATION'
old = 'クエスト操作'
[[message]]
key = 'QUEST_MSG_MENU_CANCELLATION'
old = '優先解除'
[[message]]
key = 'QUEST_MSG_MENU_PROORITY'
old = '優先クエスト'
[[message]]
key = 'QUEST_MSG_MENU_CANCEL'
old = 'クエスト破棄'
[[message]]
key = 'QUEST_MSG_MENU_MAP'
old = '地図で確認'
[[message]]
key = 'QUEST_MSG_QUESTMENU'
old = 'クエストメニュー'
[[message]]
key = 'QUEST_MSG_QUESTLIST'
old = '受注クエスト一覧'
[[message]]
key = 'QUEST_MSG_BOARD_TITLE01'
old = 'Quest Board'
[[message]]
key = 'QUEST_MSG_BOARD_TITLE02'
old = 'クエストボード'
[[message]]
key = 'QUEST_MSG_LB_REQ2'
old = '依頼'
[[message]]
key = 'QUEST_MSG_BUTTON_ACCEPT'
old = '受注する'
[[message]]
key = 'QUEST_MSG_BUTTON_CANCEL'
old = 'キャンセル'
[[message]]
key = 'QUEST_MSG_LB_SPBONUS'
old = 'Special Bonus'
[[message]]
key = 'QUEST_MSG_SUBMENU'
old = 'サブメニュー'
[[message]]
key = 'QUEST_MSG_AREAPOINT'
old = 'エリア名声度 <VAL AREA_POINT>'
[[message]]
key = 'QUEST_MSG_TAB_ALL'
old = 'すべて'
[[message]]
key = 'QUEST_MSG_TAB_HUNT'
old = '討伐'
[[message]]
key = 'QUEST_MSG_TAB_COLLECT'
old = '納品'
[[message]]
key = 'QUEST_MSG_CAUTION_FULL'
old = '''
クエスト受注数が上限に達しているため
クエストを受注できません'''
[[message]]
key = 'QUEST_MSG_CAUTION_NOTHING'
old = '現在、特別な報せはありません'
[[message]]
key = 'QUEST_MSG_BN_UNDETECTED'
old = '未公開ボーナス'
[[message]]
key = 'QUEST_MSG_BN_REPLAY'
old = '繰り返しボーナス'
[[message]]
key = 'QUEST_MSG_ACCIDENTAL'
old = 'ボードボーナス発生中！'
[[message]]
key = 'QUEST_MSG_PROGRESS_CONDITION'
old = '進行条件'
[[message]]
key = 'QUEST_MSG_HOLDING_PERIOD'
old = '開催期間'
[[message]]
key = 'QUEST_MSG_WAIT_ORDER_QUEST'
old = '受注待ちクエスト'
[[message]]
key = 'QUEST_MSG_LIST_UPDATE_ERROR'
old = 'リストの更新に失敗しました'
[[message]]
key = 'QUEST_MSG_SELECT_REWARD'
old = '選択報酬 (1つ選択)'
[[message]]
key = 'QUEST_MSG_NOTHING'
old = '現在受注しているクエストはありません'
[[message]]
key = 'QUEST_MSG_NUMBER'
old = 'No.<VAL>'
[[message]]
key = 'QUEST_MSG_REPLAY_XP_UP'
old = '経験値アップ'
[[message]]
key = 'QUEST_MSG_REPLAY_AP_UP'
old = 'エリアポイントアップ'
[[message]]
key = 'QUEST_MSG_REPLAY_RIM_UP'
old = 'リムアップ'
[[message]]
key = 'QUEST_MSG_REPLAY_GOLD_UP'
old = 'ゴールドアップ'
[[message]]
key = 'QUEST_MSG_REPLAY_SLOT_UP'
old = 'ランダム報酬枠増加'
[[message]]
key = 'QUEST_MSG_CONFIRM_QUEST_CANCEL'
old = '''
クエストを破棄しますか？

※破棄したクエストは白竜神殿などの
　拠点に入りなおすと再受注可能になります'''
[[message]]
key = 'QUEST_MSG_CONFIRM_QUEST_ORDER'
old = '''
クエストを受注します
よろしいですか？'''
[[message]]
key = 'QUEST_MSG_MENU_ORDER'
old = 'クエスト受注'
[[message]]
key = 'QUEST_MSG_SUPPORT_REWARD'
old = 'アシスト報酬'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_XP'
old = '経験値報酬が%2.1f倍（%s）'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_AP'
old = 'エリアポイント報酬が%2.1f倍（%s）'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_RIM'
old = 'リム報酬が%2.1f倍（%s）'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_GOLD'
old = 'ゴールド報酬が%2.1f倍（%s）'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_RANDOM'
old = 'ランダム報酬枠が%d増加（%s）'
[[message]]
key = 'QUEST_MSG_BONUS_CHANCE_NUMBER'
old = 'ボーナス発生まで%d回'
[[message]]
key = 'QUEST_MSG_BONUS_TIME'
old = 'ボーナス発生中'
[[message]]
key = 'QUEST_MSG_OPTION_COURSE'
old = '<OPCS>'
[[message]]
key = 'QUEST_MSG_NOTION_WAITING'
old = 'リーダーが受注時に受注待ちは解除できます'
[[message]]
key = 'QUEST_MSG_NOTION_DISABLE_PT'
old = '「パーティークエスト情報」では使用できません'
[[message]]
key = 'QUEST_MSG_NOTE_COLLISION_PROC'
old = 'リーダーとクエスト進行状況が一致していないため進行不可'
[[message]]
key = 'QUEST_MSG_ORDERED_OVER'
old = 'クエスト受注数オーバー（クエストクリア/破棄で受注可）'
[[message]]
key = 'QUEST_MSG_PARTYB_ON1'
old = 'パーティークリアボーナス対象'
[[message]]
key = 'QUEST_MSG_PARTYB_OFF1'
old = 'パーティークリアボーナス対象(取得済)'
[[message]]
key = 'QUEST_MSG_PARTYB_ON2'
old = 'クリア報酬（アイテム以外）が最大<VAL>倍！'
[[message]]
key = 'QUEST_MSG_PARTYB_OFF2'
old = '''
クリア報酬（アイテム以外）が最大<VAL>倍！
ブラッドオーブが<VAL>個獲得！'''
[[message]]
key = 'QUEST_MSG_RAIDB_TITLE'
old = 'スコア倍率ボーナス'
[[message]]
key = 'QUEST_MSG_RAIDb_BODY'
old = '<VAL>倍からスタート'
[[message]]
key = 'QUEST_MSG_OUT_LEADER'
old = 'リーダーが不在のため進行／受注不可'
[[message]]
key = 'QUEST_MSG_RANDOM_REWARD'
old = 'ランダム報酬'
[[message]]
key = 'QUEST_MSG_TIME_LIMIT'
old = '配信終了まで'
[[message]]
key = 'QUEST_MSG_NOTHING_0'
old = '---'
[[message]]
key = 'QUEST_MSG_LEADER_CONDITION'
old = 'リーダーが受注条件を満たしていません'
[[message]]
key = 'QUEST_MSG_AREA_BONUS'
old = 'ボードボーナスでクリア時の報酬が最大<VAL>倍！'
[[message]]
key = 'QUEST_MSG_LEADER_PROGRESS'
old = 'リーダーが進行条件を満たしていません'
[[message]]
key = 'QUEST_MSG_BN_UNDETECTED1'
old = '未公開ボーナス(取得済)'
[[message]]
key = 'QUEST_MSG_BN_TIMEBONUS'
old = 'タイムボーナス'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_TIMEBONUS'
old = 'スコア倍率が最大<VAL>倍！'
[[message]]
key = 'QUEST_MSG_PARTY_LARGE'
old = '特定のコンテンツ中は進行できません'
[[message]]
key = 'QUEST_MSG_SELECT_REWARD_ONLY_ONE'
old = '選択報酬'
[[message]]
key = 'QUEST_MSG_BONUS_REWARD_DAILY'
old = '''
１日１回「基本報酬」
レア素材入手可能！'''
[[message]]
key = 'QUEST_MSG_BN_DAILY'
old = 'デイリーボーナス'
[[message]]
key = 'QUEST_MSG_ENEMYINFO'
old = '魔物情報'
[[message]]
key = 'QUEST_MSG_DELIVERYINFO'
old = 'クリアに必要な納品情報'
[[message]]
key = 'QUEST_MSG_BN_ROOT'
old = 'ボーナス報酬'
[[message]]
key = 'QUEST_MSG_BONUS_ROOT'
old = '成功時に報酬を追加付与'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_TITLE_EN'
old = 'Clan Quest'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_TITLE_JP'
old = 'クランクエスト'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_CAP_ENABLE_CLEAR'
old = 'CP報酬の有効クリア回数'
[[message]]
key = 'QUEST_MSG_CLAN_QUEST_NUM_ENABLE_CLEAR'
old = '%d / %d 回'
[[message]]
key = 'QUEST_MSG_WQ_UNRELEASED_AREA'
old = '対象エリアのワールドクエストが未解放のため受注不可'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_BTN'
old = '一括クリア'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_ERR_01'
old = 'すべてのクエストがクリア状態のため、使用できません'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_CONF'
old = '''
このクエストボードから配信されている
すべてのクエストを一括してクリア状態にします
<COL ffdc78>黄金石<VAL>個</COL>を消費して、一括クリアしますか？
(所持数：<VAL>)'''
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_LACK'
old = '''
黄金石が不足しています
一括クリアするには<COL ffdc78>黄金石<VAL>個</COL>が必要です
(所持数：<VAL>)'''
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_GOTO_ONLINESHOP'
old = 'オンラインショップを開く'
[[message]]
key = 'QUEST_MSG_ASSIST_ACCEPT'
old = '条件を満たしていないためアシスト状態で受注可'
[[message]]
key = 'QUEST_MSG_SEQUENCE_DUPLICATE'
old = '同一シーケンス内の別クエストを受注中のため受注不可'
[[message]]
key = 'QUEST_MSG_CG_ROYAL'
old = 'サブストーリークエスト'
[[message]]
key = 'QUEST_MSG_PLAYABLE_DATE'
old = '配信開始：'
[[message]]
key = 'QUEST_MSG_EQUIPMENT_RESTRICTIONS'
old = '装備制限あり'
[[message]]
key = 'QUEST_MSG_HARD_QUEST_TITLE_EN'
old = 'Quest Board'
[[message]]
key = 'QUEST_MSG_HARD_QUEST_TITLE_JP'
old = 'スペシャルクエストボード'
[[message]]
key = 'QUEST_MSG_SP_ALLCLEAR_DIALOG_CONF_HARD'
old = '''
このクエストボードから配信されている
すべてのクエストを一括してクリア状態にします
<COL ffdc78>黄金石<VAL>個</COL>を消費して、一括クリアしますか？
(所持数：<VAL>)

<COL aa1414>スペシャルクエストボードは、一括クリアする度に
必要な黄金石がボード毎に増加します</COL>

<COL aa1414>PPモード中や、LVが最大の時には
報酬の経験値を入手することはできません</COL>'''
[[message]]
key = 'QUEST_MSG_LV_BONUS'
old = 'クリア報酬が最大%s倍！'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_TITLE_01'
old = 'Adventure Guide'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_TITLE_02'
old = '冒険ガイド'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_NOTHING'
old = '現在紹介出来るクエストはありません'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_01'
old = 'メインクエスト'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_02'
old = 'レベル上げミッション'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_03'
old = 'レベル上げクエスト'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_04'
old = '冒険に役立つクエスト'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_05'
old = 'ジョブクエスト'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_06'
old = 'コラボ/シーズナルクエスト'
[[message]]
key = 'QUEST_MSG_LB_OPEN_CONTENTS'
old = '解放コンテンツ'
[[message]]
key = 'QUEST_MSG_MENU_NAVI_ON'
old = 'ナビゲート設定'
[[message]]
key = 'QUEST_MSG_MENU_NAVI_OFF'
old = 'ナビゲート解除'
[[message]]
key = 'QUEST_MSG_MENU_ENTRY'
old = '参加する'
[[message]]
key = 'QUEST_MSG_OPEN_MAP_ERROR_NO_NAVI'
old = '地図で確認するには、ナビゲーションを設定してください'
[[message]]
key = 'QUEST_MSG_OPEN_MAP_ERROR_NO_MARKER'
old = '受注可能になるまで、地図で確認できません。'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_EXM_REWARD_NAME'
old = 'その他報酬'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_EXM_REWARD_INFO'
old = '詳細は参加ボタンを押して、エントリー画面でご確認ください'
[[message]]
key = 'QUEST_MSG_ADV_GUIDE_CATEGORY_07'
old = 'エリア試練/エリアミッション'
