[[message]]
key = 'msg_ShopTitle_Charges00'
old = '宿泊費無料！'
[[message]]
key = 'msg_ShopTitle_Charges01'
old = '保管ボックスの拡張枠が使用可能！'
[[message]]
key = 'msg_ShopTitle_Charges02'
old = '拠点用保管ボックスが使用可能！'
[[message]]
key = 'msg_ShopTitle_Charges03'
old = '受注上限数が増加！'
[[message]]
key = 'msg_ShopTitle_Charges04'
old = '商品%s！'
[[message]]
key = 'msg_ShopTitle_Charges05'
old = '出品可能数%s枠増加！'
[[message]]
key = 'msg_ShopTitle_Charges06'
old = '支援品%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges07'
old = '報酬アイテムのレア確率UP！'
[[message]]
key = 'msg_ShopTitle_Charges08'
old = 'リム報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges09'
old = '報酬アイテムの増加！'
[[message]]
key = 'msg_ShopTitle_Charges10'
old = 'XP報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges11'
old = 'AP報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges12'
old = 'JP報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges13'
old = 'メインポーンXP報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges14'
old = 'クラフトXP報酬%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges15'
old = 'マイ拠点へのリム転移無料！'
[[message]]
key = 'msg_ShopTitle_Charges16'
old = '無制限で利用可能！'
[[message]]
key = 'msg_ShopTitle_Charges17'
old = '取引成立後のロック時間短縮！'
[[message]]
key = 'msg_ShopTitle_Charges18'
old = '%s'
[[message]]
key = 'msg_ShopTitle_Charges19'
old = '冒険パスポート'
[[message]]
key = 'msg_ShopTitle_Charges20'
old = '報酬サポートコース'
[[message]]
key = 'msg_ShopTitle_Charges21'
old = '成長サポートコース'
[[message]]
key = 'msg_ShopTitle_Charges22'
old = 'アクションサポートコース'
[[message]]
key = 'msg_ShopTitle_Charges23'
old = 'ダブル特典コース'
[[message]]
key = 'msg_ShopTitle_Charges24'
old = 'トリプル特典コース'
[[message]]
key = 'msg_ShopTitle_Charges25'
old = 'アイテム取得数%d倍！'
[[message]]
key = 'msg_ShopTitle_Charges33'
old = 'メインポーン<UNIT JP>報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges26'
old = 'リム報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges27'
old = '報酬アイテムのレア確率UP！'
[[message]]
key = 'msg_ShopTitle_Charges28'
old = '報酬アイテムの増加！'
[[message]]
key = 'msg_ShopTitle_Charges29'
old = '<UNIT XP>報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges30'
old = 'メインポーン<UNIT XP>報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges31'
old = '<UNIT AP>報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges32'
old = '<UNIT JP>報酬%sUP！'
[[message]]
key = 'msg_ShopTitle_Charges34'
old = '解放済の礎へ転移可能！'
[[message]]
key = 'msg_ShopTitle_Charges35'
old = '料金%d%%OFF！'
[[message]]
key = 'msg_ShopTitle_Charges36'
old = '防御力%dUP！'
[[message]]
key = 'msg_ShopTitle_Charges37'
old = 'スタミナ上限%dUP！'
[[message]]
key = 'msg_ShopTitle_Charges38'
old = '体力上限%dUP！'
[[message]]
key = 'msg_ShopTitle_Charges39'
old = '助け起こされ時間短縮'
[[message]]
key = 'msg_ShopTitle_Charges40'
old = '（ポーン）'
[[message]]
key = 'msg_ShopTitle_Charges41'
old = 'スタミナ%dUP！'
[[message]]
key = 'msg_ShopTitle_Charges42'
old = '体力%dUP！'
[[message]]
key = 'msg_ShopTitle_Charges43'
old = 'ロストポーンの救出可能！'
[[message]]
key = 'msg_ShopTitle_Charges44'
old = '獲得スコア%s倍！'
[[message]]
key = 'msg_ShopTitle_Charges45'
old = '発動中'
[[message]]
key = 'msg_ShopTitle_Charges46'
old = '格納チェストの引出し%dが使用可能！'
[[message]]
key = 'msg_ShopTitle_Charges47'
old = '自動復活中！'
[[message]]
key = 'msg_ShopTitle_Charges48'
old = '自動入力アシスト！'
[[message]]
key = 'msg_ShopTitle_Charges49'
old = '被ダメージ軽減！'
[[message]]
key = 'msg_ShopTitle_Charges50'
old = '耐久力UP！'
[[message]]
key = 'msg_ShopTitle_Charges51'
old = '状態異常の蓄積軽減！'
[[message]]
key = 'msg_ShopTitle_Charges52'
old = '必要素材が格納チェストからも参照可能！'
[[message]]
key = 'msg_ShopTitle_Charges53'
old = '「<OPCS>」専用ロットが利用可能！'
[[message]]
key = 'msg_ShopTitle_Charges54'
old = '<UNTN TP>加算中！'
[[message]]
key = 'msg_ShopTitle_Charges55'
old = '<OPCS>用マンドラゴラが育成可能！'
[[message]]
key = 'msg_ShopTitle_Charges56'
old = 'メインポーンJP報酬%s倍！'
