[[message]]
key = 'sys_announce_controllernotconnect'
old = '<PFWD 0>が接続されていません'
[[message]]
key = 'sys_announce_check_strage'
old = 'ハードディスクドライブの容量をチェックしています'
[[message]]
key = 'sys_announce_notenoughstorage'
old = '''
ハードディスクドライブの空き容量が不足しています
ゲームを開始するためには
<VAL 0> 以上の空き容量が必要です
ゲームを終了して空き容量を確保してください'''
[[message]]
key = 'sys_announce_trophy'
old = ''
[[message]]
key = 'sys_announce_newsave'
old = '''
新規にセーブデータを作成しています
PCの電源を切らないでください'''
[[message]]
key = 'sys_announce_savedata_broken'
old = '''
セーブデータが破損しています
セーブデータを破棄して
新規に作成しますか？'''
[[message]]
key = 'sys_announce_ps3_loadfail'
old = '''
セーブデータをロードできませんでした
セーブデータを破棄して
新規に作成しますか？'''
[[message]]
key = 'sys_announce_notuse_anothersave'
old = '''
他のユーザーのセーブデータを
使用することはできません
セーブデータを破棄して
新規に作成します'''
[[message]]
key = 'sys_announce_goto_launcher'
old = '''
セーブデータを準備できませんでした
ランチャーへ戻ります'''
[[message]]
key = 'sys_announce_failedsave'
old = 'セーブデータの保存に失敗しました'
[[message]]
key = 'sys_announce_checkingsave'
old = '''
セーブデータをチェックしています
PCの電源を切らないでください'''
[[message]]
key = 'sys_announce_check_strage_fail'
old = '''
ハードディスクドライブ容量の
チェックに失敗しました
ランチャーへ戻ります'''
[[message]]
key = 'sys_announce_trophy_fail'
old = '''
トロフィーデータの準備に失敗しました
ランチャーへ戻ります'''
[[message]]
key = 'sys_announce_firstoption'
old = '''
操作デバイスを選択してください
※この項目はデバイス設定からいつでも変更できます'''
[[message]]
key = 'sys_announce_choice_pad'
old = '<PFWD 0>'
[[message]]
key = 'sys_announce_choice_mouse'
old = 'マウス・キーボード'
[[message]]
key = 'sys_announce_calibration'
old = '''
<PFWD 0>のボタン配置を初期化しました
ボタン配置の確認後
必要であれば配置変更を行ってください'''
[[message]]
key = 'sys_announce_saving'
old = '設定を保存します'
[[message]]
key = 'sys_announce_exit'
old = "Dragon's Dogma Online を終了しますか？"
[[message]]
key = 'sys_announce_connecting'
old = 'サーバーと通信中です'
[[message]]
key = 'sys_announce_firstoption_uisize'
old = '''
UIの表示設定を選択してください
(解像度1920×1080 以上で有効になります)'''
[[message]]
key = 'sys_announce_choice_uilarge'
old = 'UIを拡大表示する'
[[message]]
key = 'sys_announce_choice_uinormal'
old = 'UIを拡大表示しない'
[[message]]
key = 'sys_announce_firstoption_uisize_check'
old = '''
UIの表示サイズはこれでよろしいですか？
※この項目はデバイス設定からいつでも変更できます'''
