[[message]]
key = 'GREAT_PURPOSE_1'
old = 'エリアミッション《魔軍戦車カトブレパス》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_2'
old = 'エピタフロード《英霊眠りし道 ラスニテ山麓》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_3'
old = 'サブストーリー《王家を救いし料理番》を支援せよ！'
[[message]]
key = 'GREAT_PURPOSE_4'
old = 'ウォーミッション《ダクレイム砦奪還戦》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_5'
old = 'エリアミッション《古代の闇の中へ》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_6'
old = 'エピタフロード《英霊眠りし道 フェルヤナ荒原》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_7'
old = 'サブストーリー《奪還を指揮せし異才者》を支援せよ！'
[[message]]
key = 'GREAT_PURPOSE_8'
old = 'ウォーミッション《ジフール砦攻略戦》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_9'
old = 'エリアミッション《力に呑まれし王者》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_10'
old = 'エピタフロード《英霊眠りし道 メガドシスの記憶》を攻略せよ！'
[[message]]
key = 'GREAT_PURPOSE_11'
old = 'サブストーリー《暗部を暴きし暗躍者》を支援せよ！'
[[message]]
key = 'GREAT_PURPOSE_12'
old = 'ウォーミッション《霧の森の死闘》を攻略せよ！'
