[[message]]
key = 'AREA_NAME_1'
old = 'ハイデル平原'
[[message]]
key = 'AREA_NAME_2'
old = 'ブリア海岸'
[[message]]
key = 'AREA_NAME_3'
old = 'ミスリウ森林'
[[message]]
key = 'AREA_NAME_4'
old = 'ボルド鉱山'
[[message]]
key = 'AREA_NAME_5'
old = 'ダウ渓谷'
[[message]]
key = 'AREA_NAME_6'
old = 'ミスリウ森林深部'
[[message]]
key = 'AREA_NAME_7'
old = 'ディナン深層林'
[[message]]
key = 'AREA_NAME_8'
old = 'バートランド平原'
[[message]]
key = 'AREA_NAME_9'
old = 'バートランド平原北部'
[[message]]
key = 'AREA_NAME_11'
old = 'ザンドラ東部'
[[message]]
key = 'AREA_NAME_10'
old = 'ザンドラ禁域'
[[message]]
key = 'AREA_NAME_12'
old = '亡都メルゴダ'
[[message]]
key = 'AREA_NAME_13'
old = '魔赤島'
[[message]]
key = 'AREA_NAME_14'
old = 'エラン水林'
[[message]]
key = 'AREA_NAME_15'
old = 'ファーラナ平原'
[[message]]
key = 'AREA_NAME_16'
old = 'モロー樹林'
[[message]]
key = 'AREA_NAME_17'
old = 'キンガル峡谷'
[[message]]
key = 'AREA_NAME_18'
old = 'ラスニテ山麓'
[[message]]
key = 'AREA_NAME_19'
old = 'フェルヤナ荒原'
[[message]]
key = 'AREA_NAME_20'
old = 'メガドシス高地'
[[message]]
key = 'AREA_NAME_22'
old = 'メガドシスの記憶'
[[message]]
key = 'AREA_NAME_24'
old = '黒呪の迷宮'
