[[message]]
key = 'CONDITION_NAME_10'
old = '毒'
[[message]]
key = 'CONDITION_NAME_11'
old = '遅延'
[[message]]
key = 'CONDITION_NAME_12'
old = '睡眠'
[[message]]
key = 'CONDITION_NAME_13'
old = '気絶'
[[message]]
key = 'CONDITION_NAME_14'
old = '水濡れ'
[[message]]
key = 'CONDITION_NAME_15'
old = '油濡れ'
[[message]]
key = 'CONDITION_NAME_16'
old = 'スキル封印'
[[message]]
key = 'CONDITION_NAME_17'
old = '呪い'
[[message]]
key = 'CONDITION_NAME_18'
old = '軟化'
[[message]]
key = 'CONDITION_NAME_19'
old = '石化'
[[message]]
key = 'CONDITION_NAME_20'
old = '黄金化'
[[message]]
key = 'CONDITION_NAME_21'
old = '延焼'
[[message]]
key = 'CONDITION_NAME_22'
old = '凍結'
[[message]]
key = 'CONDITION_NAME_23'
old = '感電'
[[message]]
key = 'CONDITION_NAME_24'
old = '聖吸'
[[message]]
key = 'CONDITION_NAME_25'
old = '闇霧'
[[message]]
key = 'CONDITION_NAME_26'
old = '炎防低下'
[[message]]
key = 'CONDITION_NAME_27'
old = '氷防低下'
[[message]]
key = 'CONDITION_NAME_28'
old = '雷防低下'
[[message]]
key = 'CONDITION_NAME_29'
old = '聖防低下'
[[message]]
key = 'CONDITION_NAME_30'
old = '闇防低下'
[[message]]
key = 'CONDITION_NAME_31'
old = '物攻低下'
[[message]]
key = 'CONDITION_NAME_32'
old = '物防低下'
[[message]]
key = 'CONDITION_NAME_33'
old = '魔攻低下'
[[message]]
key = 'CONDITION_NAME_34'
old = '魔防低下'
[[message]]
key = 'CONDITION_NAME_35'
old = '弱化'
[[message]]
key = 'CONDITION_NAME_36'
old = '物攻上昇'
[[message]]
key = 'CONDITION_NAME_37'
old = '物防上昇'
[[message]]
key = 'CONDITION_NAME_38'
old = '魔攻上昇'
[[message]]
key = 'CONDITION_NAME_39'
old = '魔防上昇'
[[message]]
key = 'CONDITION_NAME_40'
old = '吹き飛ばし力上昇'
[[message]]
key = 'CONDITION_NAME_41'
old = '耐久力上昇'
[[message]]
key = 'CONDITION_NAME_42'
old = '生命治癒力上昇'
[[message]]
key = 'CONDITION_NAME_43'
old = '炎防上昇'
[[message]]
key = 'CONDITION_NAME_44'
old = '氷防上昇'
[[message]]
key = 'CONDITION_NAME_45'
old = '雷防上昇'
[[message]]
key = 'CONDITION_NAME_46'
old = '聖防上昇'
[[message]]
key = 'CONDITION_NAME_47'
old = '闇防上昇'
[[message]]
key = 'CONDITION_NAME_48'
old = '炎攻付加'
[[message]]
key = 'CONDITION_NAME_49'
old = '氷攻付加'
[[message]]
key = 'CONDITION_NAME_50'
old = '雷攻付加'
[[message]]
key = 'CONDITION_NAME_51'
old = '聖攻付加'
[[message]]
key = 'CONDITION_NAME_52'
old = '闇攻付加'
[[message]]
key = 'CONDITION_NAME_53'
old = '体力上昇'
[[message]]
key = 'CONDITION_NAME_54'
old = 'スタミナ上昇'
[[message]]
key = 'CONDITION_NAME_57'
old = '強化'
[[message]]
key = 'CONDITION_NAME_58'
old = '侵食・軽度'
[[message]]
key = 'CONDITION_NAME_59'
old = '侵食・重度'
[[message]]
key = 'CONDITION_NAME_60'
old = '侵食・危険'
[[message]]
key = 'CONDITION_NAME_61'
old = '侵食耐性'
[[message]]
key = 'CONDITION_NAME_62'
old = 'アイテム封印'
[[message]]
key = 'CONDITION_NAME_63'
old = '敵視上昇'
[[message]]
key = 'CONDITION_NAME_64'
old = '異界落とし'
