[[message]]
key = 'IDX_124'
old = '物理攻撃力を上昇させる'
[[message]]
key = 'IDX_149'
old = '''
状態異常【物防低下】
を付加する'''
[[message]]
key = 'IDX_126'
old = '物理防御力を上昇させる'
[[message]]
key = 'IDX_125'
old = '魔法攻撃力を上昇させる'
[[message]]
key = 'IDX_150'
old = '''
状態異常【魔防低下】
を付加する'''
[[message]]
key = 'IDX_127'
old = '魔法防御力を上昇させる'
[[message]]
key = 'IDX_132'
old = '吹き飛ばし力を上昇させる'
[[message]]
key = 'IDX_142'
old = '''
状態異常【黄金化】
を付加する'''
[[message]]
key = 'IDX_128'
old = '体力を上昇させる'
[[message]]
key = 'IDX_135'
old = '気絶攻力を上昇させる'
[[message]]
key = 'IDX_143'
old = '''
状態異常【睡眠】
を付加する'''
[[message]]
key = 'IDX_129'
old = 'スタミナを上昇させる'
[[message]]
key = 'IDX_147'
old = '''
状態異常【物攻低下】
を付加する'''
[[message]]
key = 'IDX_144'
old = '''
状態異常【石化】
を付加する'''
[[message]]
key = 'IDX_130'
old = '生命治癒力を上昇させる'
[[message]]
key = 'IDX_148'
old = '''
状態異常【魔攻低下】
を付加する'''
[[message]]
key = 'IDX_145'
old = '''
状態異常【遅延】
を付加する'''
[[message]]
key = 'IDX_131'
old = '耐久力を上昇させる'
[[message]]
key = 'IDX_136'
old = '重量を低下させる'
[[message]]
key = 'IDX_146'
old = '''
状態異常【軟化】
を付加する'''
[[message]]
key = 'IDX_137'
old = '''
状態異常【延焼】【炎防低下】【油濡れ】
を付加する'''
[[message]]
key = 'IDX_154'
old = '対敵特効【巨人】を付加する'
[[message]]
key = 'IDX_162'
old = '対敵特効【腐死】を付加する'
[[message]]
key = 'IDX_138'
old = '''
状態異常【凍結】【氷防低下】【水濡れ】
を付加する'''
[[message]]
key = 'IDX_155'
old = '対敵特効【呪詛】を付加する'
[[message]]
key = 'IDX_163'
old = '対敵特効【魔族】を付加する'
[[message]]
key = 'IDX_139'
old = '''
状態異常【感電】【雷防低下】【水濡れ】
を付加する'''
[[message]]
key = 'IDX_156'
old = '対敵特効【獣】を付加する'
[[message]]
key = 'IDX_164'
old = '対敵特効【有翼】を付加する'
[[message]]
key = 'IDX_140'
old = '''
状態異常【聖吸】【聖防低下】【スキル封印】
を付加する'''
[[message]]
key = 'IDX_157'
old = '対敵特効【侵食】を付加する'
[[message]]
key = 'IDX_165'
old = '対敵特効【竜族】を付加する'
[[message]]
key = 'IDX_141'
old = '''
状態異常【闇霧】【闇防低下】【毒】
を付加する'''
[[message]]
key = 'IDX_158'
old = '対敵特効【人間】を付加する'
[[message]]
key = 'IDX_166'
old = '対敵特効【霊体】を付加する'
[[message]]
key = 'IDX_151'
old = '対敵特効【亜人】を付加する'
[[message]]
key = 'IDX_159'
old = '対敵特効【戦甲】を付加する'
[[message]]
key = 'IDX_167'
old = '対敵特効【錬金】を付加する'
[[message]]
key = 'IDX_152'
old = '対敵特効【骸骨】を付加する'
[[message]]
key = 'IDX_160'
old = '対敵特効【造魔】を付加する'
[[message]]
key = 'IDX_161'
old = '対敵特効【軟体】を付加する'
[[message]]
key = 'IDX_153'
old = '対敵特効【鬼人】を付加する'
[[message]]
key = 'IDX_168'
old = '''
斬り崩しの予備動作が短縮され
より素早く剣を振り下ろすことができる
<COL ffdc78>LV毎に予備動作さらに短縮</COL>'''
[[message]]
key = 'IDX_169'
old = '''
えぐり突き時の攻撃速度が上昇する
<COL ffdc78>LV毎に攻撃速度がより上昇</COL>'''
[[message]]
key = 'IDX_170'
old = '''
盾弾きの発動時に敵の体勢を崩しやすくなる
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_171'
old = '''
盾弾きの発動時に敵を気絶させやすくなる
<COL ffdc78>LV毎に気絶攻力がより増加</COL>'''
[[message]]
key = 'IDX_172'
old = '''
盾弾きの発動時にスタミナが一定量回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_173'
old = '''
筋力が増加する
<COL ffdc78>LV毎に筋力がより増加</COL>'''
[[message]]
key = 'IDX_174'
old = '''
打属性攻撃によって
受けるダメージ量が軽減される
<COL ffdc78>LV毎にダメージさらに軽減</COL>'''
[[message]]
key = 'IDX_175'
old = '''
弓の移動射ちの際、矢が照準からぶれなくなる
<COL ffdc78>LV毎にぶれ幅がさらに軽減</COL>'''
[[message]]
key = 'IDX_176'
old = '''
一度に矢筒に補充できる矢の本数が増加する
<COL ffdc78>LV毎に矢の装填数がより増加</COL>'''
[[message]]
key = 'IDX_177'
old = '''
達人装填の成功時にスタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_178'
old = '''
状態異常を引き起こす矢の威力が増加する
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_179'
old = '''
達人装填のジャストタイミングの受付時間が
延長されより成功率が上昇する
<COL ffdc78>LV毎に受付時間がより延長</COL>'''
[[message]]
key = 'IDX_180'
old = '''
吹き飛ばし力が上昇し、
敵の体勢を崩しやすくなる
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_181'
old = '''
射属性攻撃によって
受けるダメージ量が軽減される
<COL ffdc78>LV毎にダメージさらに軽減</COL>'''
[[message]]
key = 'IDX_182'
old = '''
ヒールオーラ、セイントオーラ展開時の
スタミナ消費量が軽減される
<COL ffdc78>LV毎にスタミナ消費がさらに減少</COL>'''
[[message]]
key = 'IDX_183'
old = '''
フィールドシフト時に
敵の注目を集めにくくする
<COL ffdc78>LV毎に敵からの注目度がさらに減少</COL>'''
[[message]]
key = 'IDX_184'
old = '''
ヒールオーラ展開時に
敵から注目されにくくなる
<COL ffdc78>LV毎に敵からの注目度がさらに減少</COL>'''
[[message]]
key = 'IDX_185'
old = '''
表出させたシークレットコア出現時間が
延長される
<COL ffdc78>LV毎に出現時間がより延長</COL>'''
[[message]]
key = 'IDX_186'
old = '''
助け起こしたパーティーメンバーの
最大体力が一定時間増加する
<COL ffdc78>LV毎に効果持続時間がより延長</COL>'''
[[message]]
key = 'IDX_187'
old = '''
受けるダメージ量が軽減される
<COL ffdc78>LV毎にダメージさらに軽減</COL>'''
[[message]]
key = 'IDX_188'
old = '''
アトラクト発動時に
より敵の注目を集めるようになる
<COL ffdc78>LV毎に敵からの注目度がより増加</COL>'''
[[message]]
key = 'IDX_189'
old = '''
フォースバーストで
より敵を状態異常にかかりやすくする
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_190'
old = '''
フォースエンチャントの効果持続時間が
延長される
<COL ffdc78>LV毎に効果持続時間がより延長</COL>'''
[[message]]
key = 'IDX_191'
old = '''
シールドシーケンスを行ったときに
スタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_192'
old = '''
フォースゲージの消費時に少しゲージが残る
<COL ffdc78>LV毎にゲージ残量が増加</COL>'''
[[message]]
key = 'IDX_193'
old = '''
物理防御力と魔法防御力が増加する
<COL ffdc78>LV毎に物理/魔法防御力がより増加</COL>'''
[[message]]
key = 'IDX_194'
old = '''
最大体力が増加する
<COL ffdc78>LV毎に最大体力がより増加</COL>'''
[[message]]
key = 'IDX_195'
old = '''
白竜神殿から出てしばらくの間
最大体力が増加する
<COL ffdc78>LV毎に最大体力がより増加</COL>'''
[[message]]
key = 'IDX_196'
old = '''
斬属性攻撃によって
受けるダメージ量が軽減される
<COL ffdc78>LV毎にダメージさらに軽減</COL>'''
[[message]]
key = 'IDX_197'
old = '''
シーカーロープの飛距離が延長される
<COL ffdc78>LV毎に飛距離がより延長</COL>'''
[[message]]
key = 'IDX_198'
old = '''
シーカーロープでの移動後、接触時に繰り出す
打撃攻撃で敵の体勢を崩しやすくなる
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_199'
old = '''
転身の速度が上昇する
<COL ffdc78>LV毎に速度がより上昇</COL>'''
[[message]]
key = 'IDX_200'
old = '''
二段跳びの高度が上昇する
<COL ffdc78>LV毎に高度がより上昇</COL>'''
[[message]]
key = 'IDX_202'
old = '''
しがみつき時に与えるダメージ量が
大きく増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_203'
old = '''
怒り状態の敵にしがみついたとき
揺さぶりによって敵のスタミナを
より奪いやすくなる
<COL ffdc78>LV毎に奪う敵スタミナ量がより増加</COL>'''
[[message]]
key = 'IDX_204'
old = '''
しがみつき時に受けるダメージ量が軽減される
<COL ffdc78>LV毎にダメージさらに軽減</COL>'''
[[message]]
key = 'IDX_201'
old = '''
回避行動時の移動距離が延長される
<COL ffdc78>LV毎に移動距離がより延長</COL>'''
[[message]]
key = 'IDX_205'
old = '''
空中攻撃の威力が増加する
<COL ffdc78>LV毎に威力がより増加</COL>'''
[[message]]
key = 'IDX_206'
old = '''
高所からのジャンプ降下時、
落差が大きいほど空中攻撃力の増加幅が
拡張される
<COL ffdc78>LV毎に増加幅がより拡張</COL>'''
[[message]]
key = 'IDX_207'
old = '''
マジックトラップの展開時に
より敵の体勢を崩しやすくなる
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_208'
old = '''
スペリング入力の成功時にスタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_209'
old = '''
スペリングの入力難度が低くなり
魔法効果増大が狙いやすくなる
<COL ffdc78>LV毎に難度がより低下</COL>'''
[[message]]
key = 'IDX_210'
old = '''
バックムーブが魔法詠唱中でも
行えるようになり
詠唱ゲージを一定量保持して詠唱を継続できる
<COL ffdc78>LV毎にゲージ保持量がより増加</COL>'''
[[message]]
key = 'IDX_212'
old = '''
火属性攻撃によって
与えるダメージ量が増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_213'
old = '''
氷属性攻撃によって
与えるダメージ量が増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_214'
old = '''
雷属性攻撃によって
与えるダメージ量が増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_215'
old = '''
聖属性攻撃によって
与えるダメージ量が増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_216'
old = '''
闇属性攻撃によって
与えるダメージ量が増加する
<COL ffdc78>LV毎にダメ―ジがより増加</COL>'''
[[message]]
key = 'IDX_217'
old = '''
魔力が増加する
<COL ffdc78>LV毎に魔力がより増加</COL>'''
[[message]]
key = 'IDX_211'
old = '''
魔法詠唱中にスタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_218'
old = '''
魔眼により複数の攻撃対象を捕捉した際、
魔力増加速度が上昇する
<COL ffdc78>LV毎に増加速度がより上昇</COL>'''
[[message]]
key = 'IDX_219'
old = '''
魔眼による捕捉時間２周目満了時、
強力な魔矢を放てるジャストタイミングが
延長され、成功率が上がる
<COL ffdc78>LV毎に受付時間がより延長</COL>'''
[[message]]
key = 'IDX_220'
old = '''
魔矢の飛行速度が上昇する
<COL ffdc78>LV毎に速度がより上昇</COL>'''
[[message]]
key = 'IDX_221'
old = '''
回復・治療系の作用を持つ魔矢から
生み出された魔法球の効果持続時間が
延長される
<COL ffdc78>LV毎に持続時間がより延長</COL>'''
[[message]]
key = 'IDX_222'
old = '''
癒しの装の回復効果が上昇する
<COL ffdc78>LV毎に回復力がより上昇</COL>'''
[[message]]
key = 'IDX_223'
old = '''
敵にダメージを与えた時、体力が回復する
<COL ffdc78>LV毎に回復力がより上昇</COL>'''
[[message]]
key = 'IDX_224'
old = '''
生命治癒力が増加し、
体力の治癒上限値が低下しにくくなる
<COL ffdc78>LV毎に生命治癒力がより増加</COL>'''
[[message]]
key = 'IDX_225'
old = '''
炎属性攻撃を対象に当てた際
延焼の状態異常にかかりやすくなる
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_226'
old = '''
氷属性攻撃を対象に当てた際
凍結の状態異常にかかりやすくなる
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_227'
old = '''
雷属性攻撃を対象に当てた際
感電の状態異常にかかりやすくなる
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_228'
old = '''
聖属性攻撃を対象に当てた際
聖吸の状態異常にかかりやすくなる
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_229'
old = '''
闇属性攻撃を対象に当てた際
闇霧の状態異常にかかりやすくなる
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_230'
old = '''
カウンター攻撃でリベンジゲージが
たまりやすくなる
<COL ffdc78>LV毎にゲージ蓄積量がより増加</COL>'''
[[message]]
key = 'IDX_231'
old = '''
リベンジゲージ最大時に防御力が増加し、
攻撃を受けても体勢を崩されにくくなる
<COL ffdc78>LV毎に物理防御力/耐久力がより増加</COL>'''
[[message]]
key = 'IDX_232'
old = '''
魔人斬り、真・魔人斬りの溜め満了
ジャストタイミングが延長され、
成功率が上がる
<COL ffdc78>LV毎に受付時間がより延長</COL>'''
[[message]]
key = 'IDX_233'
old = '''
リベンジゲージ満了時、
魔人斬り、真・魔人斬りで
繰り出す初動攻撃の吹き飛ばし力が増加する
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_235'
old = '''
気絶攻力が上昇し、敵を気絶させやすくなる
<COL ffdc78>LV毎に気絶攻力がより増加</COL>'''
[[message]]
key = 'IDX_236'
old = '''
チャンス攻力が上昇し、怒り状態の強敵を
ダウンさせやすくなる
<COL ffdc78>LV毎にチャンス攻力がより増加</COL>'''
[[message]]
key = 'IDX_237'
old = '''
耐久力が上昇し、体勢を崩されにくくなる
<COL ffdc78>LV毎に耐久力がより増加</COL>'''
[[message]]
key = 'IDX_234'
old = '''
溜め攻撃で、より敵の体勢を崩しやすくなる
<COL ffdc78>LV毎に吹き飛ばし力がより増加</COL>'''
[[message]]
key = 'IDX_238'
old = '''
攻撃時に、敵に与える錬成値が上昇する
<COL ffdc78>LV毎に錬成値がより増加</COL>'''
[[message]]
key = 'IDX_239'
old = '''
エリクシル発動時、
変換する状態異常値が上昇する
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_240'
old = '''
アルケム・フーガで配置される錬成物質の
持続時間が延長される
<COL ffdc78>LV毎に持続時間がより延長</COL>'''
[[message]]
key = 'IDX_241'
old = '''
エリクシル発動の予備動作が短縮される
<COL ffdc78>LV毎に予備動作さらに短縮</COL>'''
[[message]]
key = 'IDX_242'
old = '''
アルケム・フーガ成功時にスタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_243'
old = '''
スタミナの回復速度が上昇する
<COL ffdc78>LV毎にスタミナ回復速度がより上昇</COL>'''
[[message]]
key = 'IDX_244'
old = '''
カスタムスキル使用時の
スタミナ消費量が軽減される
<COL ffdc78>LV毎にスタミナ消費がさらに減少</COL>'''
[[message]]
key = 'IDX_245'
old = '''
最大スタミナが増加する
<COL ffdc78>LV毎に最大スタミナがより増加</COL>'''
[[message]]
key = 'IDX_246'
old = '''
各種回復アイテムを使ったときに
より高い効果が得られる
<COL ffdc78>LV毎に効果がより上昇</COL>'''
[[message]]
key = 'IDX_247'
old = '''
ブースト中のスピリットゲージ減少速度が
低下する
<COL ffdc78>LV毎により減少速度がさらに低下</COL>'''
[[message]]
key = 'IDX_248'
old = '''
敵の攻撃をスカー・ムーヴで回避すると
スタミナが回復する
<COL ffdc78>LV毎にスタミナ回復量がより増加</COL>'''
[[message]]
key = 'IDX_249'
old = '''
エイド／エイド・モールの展開時間が
延長される
<COL ffdc78>LV毎に展開時間がより延長</COL>'''
[[message]]
key = 'IDX_250'
old = '''
ブーストを発動すると
物理防御力と魔法防御力を一定時間上昇させる
<COL ffdc78>LV毎に効果時間がより上昇</COL>'''
[[message]]
key = 'IDX_251'
old = '''
敵の攻撃をスカー・ムーヴで回避した場合の
スピリットゲージの上昇量が増加する
<COL ffdc78>LV毎にスピリットゲージがより増加</COL>'''
[[message]]
key = 'IDX_252'
old = '''
エンチャントを受けた際に
敵に与えるダメージ量がより増加する
<COL ffdc78>LV毎にダメージがより増加</COL>'''
[[message]]
key = 'IDX_253'
old = '''
魔力スタックが2以上の時に、
筋力と魔力が増加する
<COL ffdc78>LV毎に筋力と魔力がより増加</COL>'''
[[message]]
key = 'IDX_254'
old = '''
魔印の減退速度が低下する
<COL ffdc78>LV毎により減退速度がさらに低下</COL>'''
[[message]]
key = 'IDX_255'
old = '''
属性の付与されたルイン・ブレードで
より敵を状態異常にかかりやすくする
<COL ffdc78>LV毎に状態異常値がより増加</COL>'''
[[message]]
key = 'IDX_256'
old = '''
全ての純魔法の消費時に少し魔力が残る
<COL ffdc78>LV毎に魔力残量がより増加</COL>'''
[[message]]
key = 'IDX_257'
old = '''
全ての補助魔法の消費時に少し魔力が残る
<COL ffdc78>LV毎に魔力残量がより増加</COL>'''
[[message]]
key = 'IDX_258'
old = '''
スタミナを一定量消費するスキルを
使用した際に一定確率で消費を無効にする
<COL ffdc78>LV毎に無効になる確率がより増加</COL>'''
[[message]]
key = 'IDX_259'
old = '''
フォースゲージ／リベンジゲージ／魔力ゲージ
を消費するスキルを使用した際に
一定確率で消費を無効にする
<COL ffdc78>LV毎に無効になる確率がより増加</COL>'''
[[message]]
key = 'IDX_260'
old = '''
疲労攻力が上昇する
<COL ffdc78>LV毎に疲労攻力がより増加</COL>'''
